# This tells Netlify your build command and where the final site is located.
[build]
  command = "npm run build"
  publish = "dist" # IMPORTANT: Change to "build" if you are using Create React App

# This is the redirect rule.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200